#!/usr/bin/env bash
#
# skill-drift.sh — Detect when .ai/skills docs drift from code reality.
#
# Parses the Module Routing table from CLAUDE.md (single source of truth),
# compares each skill file's last-modified commit against code changes
# in its domain, and reports drift.
#
# Usage:
#   .ai/skills/Tools/skill-drift.sh          # check all skills
#   .ai/skills/Tools/skill-drift.sh --quiet  # exit code only (for CI/hooks)
#   .ai/skills/Tools/skill-drift.sh --json   # JSON output (for CI/PR comments)
#
# Generated by RepoSkills. Customise CROSS_CUTTING and SCAN_DIRS for your repo.

set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

# ─── Bash version check ────────────────────────────────────────────
# Associative arrays require bash 4+. macOS ships bash 3.2.
if ((BASH_VERSINFO[0] < 4)); then
    echo "skill-drift.sh requires bash 4+. Found: $BASH_VERSION" >&2
    echo "On macOS: brew install bash" >&2
    exit 1
fi

QUIET=false
JSON=false
for arg in "$@"; do
    case "$arg" in
        --quiet) QUIET=true ;;
        --json)  JSON=true; QUIET=true ;;
    esac
done

# ─── Test File Exclusions ───────────────────────────────────────────
# Files matching these patterns are excluded from drift detection.
# Test changes don't affect what a skill needs to document.

# File name patterns (matched against basename)
TEST_FILE_PATTERNS=(
    '*_test.go'                # Go
    'test_*.py'                # Python (prefix)
    '*_test.py'                # Python (suffix)
    'conftest.py'              # Python (pytest)
    '*.test.ts' '*.test.tsx'   # TypeScript
    '*.spec.ts' '*.spec.tsx'   # TypeScript (spec)
    '*.test.js' '*.test.jsx'   # JavaScript
    '*.spec.js' '*.spec.jsx'   # JavaScript (spec)
    '*Tests.cs'                # C#
    '*Test.java' '*Tests.java' # Java
)

# Directory patterns — any file under these directories is excluded
TEST_DIR_PATTERNS=(
    'testdata'
    '__tests__'
    'tests'
    'test'
    '.test'
)

is_test_file() {
    local filepath="$1"
    local basename="${filepath##*/}"
    local dirpath="${filepath%/*}"

    for pattern in "${TEST_DIR_PATTERNS[@]}"; do
        case "$dirpath" in
            "$pattern"|"$pattern/"*|*"/$pattern"|*"/$pattern/"*) return 0 ;;
        esac
    done

    for pattern in "${TEST_FILE_PATTERNS[@]}"; do
        # shellcheck disable=SC2254
        case "$basename" in $pattern) return 0 ;; esac
    done

    return 1
}

filter_test_files() {
    while IFS= read -r filepath; do
        [[ -z "$filepath" ]] && continue
        is_test_file "$filepath" || echo "$filepath"
    done
}

# ─── Cross-cutting packages (optional) ─────────────────────────────
# Directories intentionally not mapped to a module skill.
# These ONLY affect the "unmapped directories" report — they suppress
# noise from shared utility directories that don't warrant their own skill.
# The core drift detection (skill-vs-code comparison) ignores this array.
#
# Leave empty if you don't have many shared utility directories.
# Populate if the unmapped report would otherwise be too noisy to be useful.
CROSS_CUTTING=(
    # Example: lib/utils lib/helpers src/common src/shared
)

is_cross_cutting() {
    local dir="$1"
    for cc in "${CROSS_CUTTING[@]}"; do
        [[ "$dir" == "$cc" || "$dir" == "$cc/"* ]] && return 0
    done
    return 1
}

# ─── Scan directories for unmapped coverage ────────────────────────
# Top-level directory globs to check for modules not in the routing table.
# CUSTOMISE: Add your repo's top-level module directory patterns below.
SCAN_DIRS=(
    # Example: 'src/*/' 'pkg/*/' 'cmd/*/' 'services/*/'
)

# ─── Parse routing from CLAUDE.md ──────────────────────────────────
# CLAUDE.md Module Routing table is the single source of truth.
# Format: | description | `skill_file` | working in `dir/`, `dir/`, ... |

declare -A DIR_TO_SKILLS   # dir -> space-separated skill files

parse_routing() {
    local claude_md="CLAUDE.md"
    if [[ ! -f "$claude_md" ]]; then
        echo "ERROR: CLAUDE.md not found at repo root" >&2
        exit 1
    fi

    # Match table rows containing skill file paths
    while IFS= read -r line; do
        # Extract skill file from backticks (column 2)
        skill=$(echo "$line" | grep -oE '\.ai/skills/modules/[a-z0-9_-]+\.md' | head -1)
        [[ -z "$skill" ]] && continue

        # Extract directory paths from USE WHEN column
        # Paths are backtick-wrapped with trailing slash: `pkg/sync/`
        use_when="${line##*Load these skills |}"
        dirs=$(echo "$use_when" | { grep -oE '`[a-zA-Z0-9/_-]+/`' || true; } | tr -d '`' | sed 's|/$||')

        for dir in $dirs; do
            existing="${DIR_TO_SKILLS[$dir]:-}"
            if [[ -n "$existing" ]]; then
                # Avoid duplicates
                if [[ "$existing" != *"$skill"* ]]; then
                    DIR_TO_SKILLS[$dir]="$existing $skill"
                fi
            else
                DIR_TO_SKILLS[$dir]="$skill"
            fi
        done
    done < <(grep '^|.*\.ai/skills/modules/' "$claude_md")
}

parse_routing

# ─── Helper functions ──────────────────────────────────────────────

last_modified_commit() {
    git log -1 --format=%H -- "$1" 2>/dev/null || echo ""
}

commit_date() {
    git log -1 --format=%cd --date=short "$1" 2>/dev/null || echo "unknown"
}

short_hash() {
    git rev-parse --short "$1" 2>/dev/null || echo "unknown"
}

dir_mentioned_in_file() {
    local dir="$1"
    local file="$2"
    local basename="${dir##*/}"
    # Check for full path (pkg/handlers) or basename (handlers)
    grep -qE "$dir|$basename" "$file" 2>/dev/null
}

# ─── Main: Check drift per skill ──────────────────────────────────

declare -A skill_changed_dirs   # skill -> "dir(N) dir(N) ..."
declare -A skill_commits        # skill -> anchor commit hash
declare -A skill_not_mentioned  # skill -> dirs not mentioned in skill

for dir in "${!DIR_TO_SKILLS[@]}"; do
    [[ ! -d "$dir" ]] && continue
    skills="${DIR_TO_SKILLS[$dir]}"

    for skill in $skills; do
        [[ ! -f "$skill" ]] && continue

        # Get skill's anchor commit
        if [[ -z "${skill_commits[$skill]:-}" ]]; then
            skill_commits[$skill]=$(last_modified_commit "$skill")
        fi
        anchor="${skill_commits[$skill]}"
        [[ -z "$anchor" ]] && continue

        # Find non-test, non-doc changes since the skill was last updated
        all_changes=$(git diff "$anchor"...HEAD --name-only -- "$dir/" 2>/dev/null || true)
        changes=""
        if [[ -n "$all_changes" ]]; then
            no_docs=$(echo "$all_changes" | { grep -v '\.md$' || true; })
            if [[ -n "$no_docs" ]]; then
                changes=$(echo "$no_docs" | filter_test_files)
            fi
        fi

        if [[ -n "$changes" ]]; then
            change_count=$(echo "$changes" | wc -l | tr -d ' ')
            existing="${skill_changed_dirs[$skill]:-}"
            if [[ -n "$existing" ]]; then
                skill_changed_dirs[$skill]="$existing $dir($change_count)"
            else
                skill_changed_dirs[$skill]="$dir($change_count)"
            fi

            if ! dir_mentioned_in_file "$dir" "$skill"; then
                existing_nm="${skill_not_mentioned[$skill]:-}"
                if [[ -n "$existing_nm" ]]; then
                    skill_not_mentioned[$skill]="$existing_nm $dir"
                else
                    skill_not_mentioned[$skill]="$dir"
                fi
            fi
        fi
    done
done

# ─── Report: Skills with drift ────────────────────────────────────

drift_found=false

for skill in $(echo "${!skill_changed_dirs[@]}" | tr ' ' '\n' | sort -u); do
    dirs="${skill_changed_dirs[$skill]}"
    [[ -z "$dirs" ]] && continue

    if [[ "$drift_found" == false ]]; then
        $QUIET || echo ""
        $QUIET || echo "Skill drift detected:"
        $QUIET || echo ""
        drift_found=true
    fi

    anchor="${skill_commits[$skill]}"
    anchor_date=$(commit_date "$anchor")
    anchor_short=$(short_hash "$anchor")
    # Count commits touching the changed dirs since anchor
    dir_list=$(echo "$dirs" | sed 's/([0-9]*)//g')
    commit_count=$(git rev-list "$anchor"..HEAD -- $dir_list 2>/dev/null | wc -l | tr -d ' ')

    if ! $QUIET; then
        echo "  $skill (last updated: $anchor_short, $anchor_date)"
        echo "    $commit_count commit(s) with changes in its domain since last skill update"
        echo "    Directories changed: $(echo "$dirs" | sed 's/ /, /g')"

        not_mentioned="${skill_not_mentioned[$skill]:-}"
        if [[ -n "$not_mentioned" ]]; then
            echo "    ** Not mentioned in skill: $not_mentioned"
        fi
        echo ""
    fi
done

# ─── Report: Unmapped directories ─────────────────────────────────

unmapped_found=false

for glob_pattern in "${SCAN_DIRS[@]}"; do
    for dir in $glob_pattern; do
        dir="${dir%/}"
        [[ ! -d "$dir" ]] && continue
        is_cross_cutting "$dir" && continue
        [[ -n "${DIR_TO_SKILLS[$dir]:-}" ]] && continue

        if [[ "$unmapped_found" == false ]]; then
            $QUIET || echo "Directories with no skill coverage:"
            $QUIET || echo ""
            unmapped_found=true
        fi
        $QUIET || echo "  $dir/ — not in CLAUDE.md Module Routing table"
    done
done

# ─── JSON output (for CI integration) ────────────────────────────

if $JSON; then
    json_drifts="["
    first=true
    for skill in $(echo "${!skill_changed_dirs[@]}" | tr ' ' '\n' | sort -u); do
        dirs="${skill_changed_dirs[$skill]}"
        [[ -z "$dirs" ]] && continue
        anchor="${skill_commits[$skill]}"
        anchor_date=$(commit_date "$anchor")
        not_mentioned="${skill_not_mentioned[$skill]:-}"
        dir_list=$(echo "$dirs" | sed 's/([0-9]*)//g')
        commit_count=$(git rev-list "$anchor"..HEAD -- $dir_list 2>/dev/null | wc -l | tr -d ' ')

        # Find first changed file in this skill's domain for inline comment placement
        first_file=""
        for d in $dir_list; do
            candidate=$(git diff "$anchor"...HEAD --name-only -- "$d/" 2>/dev/null | { grep -v '\.md$' || true; } | filter_test_files | head -1 || true)
            if [[ -n "$candidate" ]]; then
                first_file="$candidate"
                break
            fi
        done

        $first || json_drifts="$json_drifts,"
        first=false
        json_drifts="$json_drifts{\"skill\":\"$skill\",\"anchor_date\":\"$anchor_date\",\"commit_count\":$commit_count,\"dirs\":\"$(echo "$dirs" | sed 's/ /, /g')\",\"not_mentioned\":\"$not_mentioned\",\"first_file\":\"$first_file\"}"
    done
    json_drifts="$json_drifts]"

    json_unmapped="["
    first=true
    for glob_pattern in "${SCAN_DIRS[@]}"; do
        for dir in $glob_pattern; do
            dir="${dir%/}"
            [[ ! -d "$dir" ]] && continue
            is_cross_cutting "$dir" && continue
            [[ -n "${DIR_TO_SKILLS[$dir]:-}" ]] && continue
            $first || json_unmapped="$json_unmapped,"
            first=false
            json_unmapped="$json_unmapped\"$dir\""
        done
    done
    json_unmapped="$json_unmapped]"

    echo "{\"drifts\":$json_drifts,\"unmapped\":$json_unmapped}"
    [[ "$json_drifts" == "[]" && "$json_unmapped" == "[]" ]] && exit 0 || exit 1
fi

# ─── Summary ──────────────────────────────────────────────────────

if [[ "$drift_found" == false && "$unmapped_found" == false ]]; then
    $QUIET || echo "Skill drift check: all skills up to date."
    exit 0
else
    if ! $QUIET; then
        echo "---"
        echo "To resolve: update the skill file(s) and/or CLAUDE.md routing table."
    fi
    exit 1
fi
