#!/usr/bin/env bash
#
# skill-drift-hook.sh — Install or remove skill drift detection as a git hook.
#
# Usage:
#   .ai/skills/Tools/skill-drift-hook.sh install [pre-commit|post-commit]
#   .ai/skills/Tools/skill-drift-hook.sh uninstall
#   .ai/skills/Tools/skill-drift-hook.sh status
#
# Note: Git hooks are LOCAL to each developer's clone. Installing this hook
# only benefits YOU — other team members won't see drift warnings unless they
# also install it. For team-wide coverage, use CI integration instead
# (see skill-drift.sh --json for CI-friendly output).
#
# Generated by RepoSkills.

set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

HOOKS_DIR=".git/hooks"
START_MARKER="# skill-drift-hook-start"
END_MARKER="# skill-drift-hook-end"

usage() {
    echo "Usage: $0 {install|uninstall|status}"
    echo ""
    echo "  install [hook-type]  Install drift check as a git hook (default: post-commit)"
    echo "  uninstall            Remove drift check from all git hooks"
    echo "  status               Show current hook installation status"
    echo ""
    echo "Hook types: pre-commit, post-commit"
    echo ""
    echo "Note: Git hooks are local to each clone — only YOU see drift warnings."
    echo "For team-wide coverage, use CI integration instead."
    exit 1
}

drift_block() {
    cat <<'BLOCK'
# skill-drift-hook-start (do not edit this block)
# Skill drift check (non-blocking — informational only)
if [[ -x .ai/skills/Tools/skill-drift.sh ]]; then
    .ai/skills/Tools/skill-drift.sh 2>/dev/null || true
fi
# skill-drift-hook-end
BLOCK
}

install_hook() {
    local hook_type="${1:-post-commit}"

    case "$hook_type" in
        pre-commit|post-commit) ;;
        *) echo "Unknown hook type: $hook_type (use pre-commit or post-commit)" >&2; exit 1 ;;
    esac

    local hook_file="$HOOKS_DIR/$hook_type"

    if [[ -f "$hook_file" ]]; then
        if grep -q "$START_MARKER" "$hook_file"; then
            echo "Drift hook already installed in $hook_type"
            return 0
        fi
        # Append to existing hook
        echo "" >> "$hook_file"
        drift_block >> "$hook_file"
        echo "Drift hook appended to existing $hook_type hook"
    else
        # Create new hook
        {
            echo "#!/usr/bin/env bash"
            echo ""
            drift_block
        } > "$hook_file"
        chmod +x "$hook_file"
        echo "Drift hook installed as $hook_type hook"
    fi
}

uninstall_hook() {
    local found=false
    for hook_type in pre-commit post-commit; do
        local hook_file="$HOOKS_DIR/$hook_type"
        [[ -f "$hook_file" ]] || continue
        if grep -q "$START_MARKER" "$hook_file"; then
            # Remove the drift block between markers
            sed -e "/$START_MARKER/,/$END_MARKER/d" "$hook_file" > "$hook_file.tmp" && mv "$hook_file.tmp" "$hook_file"
            # If the hook file is now just a shebang + whitespace, remove it
            if [[ $(grep -cv '^\s*$\|^#!' "$hook_file") -eq 0 ]]; then
                rm "$hook_file"
                echo "Removed $hook_type hook (was only drift check)"
            else
                echo "Removed drift check from $hook_type hook"
            fi
            found=true
        fi
    done

    if ! $found; then
        echo "No drift hooks found to uninstall"
    fi
}

show_status() {
    local found=false
    for hook_type in pre-commit post-commit; do
        local hook_file="$HOOKS_DIR/$hook_type"
        if [[ -f "$hook_file" ]] && grep -q "$START_MARKER" "$hook_file"; then
            echo "Installed: $hook_type"
            found=true
        fi
    done

    if ! $found; then
        echo "Not installed (no drift hooks found)"
        echo ""
        echo "Install with: .ai/skills/Tools/skill-drift-hook.sh install"
        echo "For team-wide coverage, use CI integration instead."
    fi
}

case "${1:-}" in
    install)   install_hook "${2:-post-commit}" ;;
    uninstall) uninstall_hook ;;
    status)    show_status ;;
    *)         usage ;;
esac
